name: Parse and update

on:
  schedule:
    # Every Monday at 1PM UTC (9AM EST)
    - cron: "0 13 * * 1"
  workflow_dispatch:

jobs:
  format-code:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
      - run: npm run update

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
